# Generated by Django 4.2.24 on 2025-10-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='noise_level',
            field=models.CharField(verbose_name='Уровень шума, дБа'),
        ),
    ]
